//
//  WineType.swift
//  Wine Flight
//
//  Created by James McDougall on 1/5/21.
//

import Foundation

enum WineType: String {
    case cabernetSauvignon = "Cabernet Sauvignon"
    case chardonnay = "Chardonnay"
    case merlot = "Merlot"
    case pinotNoir = "Pinot Noir"
    case grenache = "Grenache/Garnacha"
    case syrah = "Syrah/Shiraz"
    case cabernetFranc = "Cabernet Franc"
    case petitVerdot = "Petit Verdot"
    case mourvedre = "Mouvedre/Mataro/Monastrell/Garrut"
    case malbec = "Malbec"
    case sangiovese = "Sangiovese"
    case savignonBlanc = "Sauvignon Blanc"
    case rieseling = "Riesling"
    case nebbiolo = "Nebbiolo"
    case portVarieties = "Port Varieties"
    case tempranillo = "Tempranillo/Tinto Fino/Tinta Roriz"
    case petiteSirah = "Petite Sirah"
    case grunerVeltliner = "grunerVeltliner"
    case pinotMeunier = "Pinot Meunier"
    case semillion = "Semillion"
    case tourigaFranca = "Toura Franca"
    case tourigaNacional = "Touriga Nacional"
    case zifandel = "Zifandel"
    case carignan = "Carignan/Carinena"
    case gamay = "Gamay"
    case roussanne = "Roussanne"
    case viognier = "Viognier"
    case cheninBlanc = "Chenin Blanc"
    case cisnault = "Cisnault"
    case corvina = "Corvina"
    case pedroXimenez = "Pedro Ximenez"
    case pinotGris = "Pinot Grigio"
    case clairette = "Clairette"
    case grenacheBlanc = "Grenache Blanc"
    case rodinella = "Rodinella"
    case alicanteBouschet = "Alicante Bouschet"
    case arneis = "Arneis"
    case graciano = "Graciano"
    case palomino = "Palomino"
    case trincadeira = "Trincadeira"
    case albarino = "Alberino/Alvarinho"
    case bourboulenc = "Bourboulenc"
    case carmenere = "Carmenere"
    case corvinone = "Corvinone"
    case glera = "Glera"
    case malvasia = "Malvasia"
    case muscat = "Muscat"
    case nerelloCappuccio = "Nerello Cappuccio"
    case nerelloMascalese = "Narello Mascalese"
    case sousao = "Sousao/Vinhao"
    case tintaBarroca = "Tinta Barroca"
    case tintaCao = "Tinta Cao"
    case vermentino = "Vermentino"
    case zweigelt = "Zweigelt"
    case aglianico = "Agliancio"
    case albillo = "Albillo"
    case blaufrankisch = "Blaufrankisch"
    case canaiolo = "Canaiolo"
    case furmint = "Furmint"
    case garaganega = "Garanega"
    case greco = "Greco"
    case grillo = "Grillo"
    case macabeo = "Macabeo"
    case mencia = "Mencia/Jaen"
    case molinara = "Molinara"
    case moscatel = "Moscatel"
    case parellada = "Parellada"
    case pinotBianco = "PinotBianco/Pinot Blanc"
}
